apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-monitoring
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: dev
  source:
    repoURL: https://github.com/DACHANCHOI/k8-monitoring.git
    targetRevision: HEAD
    path: app-of-monitoring
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    # automated:
    #   prune: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=background