{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, exported_namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(kube_service_created{exported_namespace=\"$Namespace\", exported_service!=\"kubernetes\"},exported_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"$Namespace\", image=\"\", pod=~\"$Service.*\"}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{namespace=\"$Namespace\", image=\"\", pod=~\"$Service.*\"}"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{exported_namespace=\"$Namespace\", pod=~\"$Service.*\"})"
    }
   ]
  }
 ]
}