autoscaling:
  enabled: false

testFramework:
  enabled: false

service:
  enabled: true
  type: NodePort
  nodePort: 32081

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

grafana.ini:
 server:
    root_url: https://0f9e-221-143-104-50.jp.ngrok.io