repoURL: 'https://github.com/iamchoiz/k8-monitoring.git'
apps:
  - name: prometheus
    project: monitoring
    namespace: monitoring
    source:
      path: prometheus/charts/prometheus
  - name: grafana
    project: monitoring
    namespace: monitoring
    source:
      path: grafana
      customValues: true
      values: 
        - values-local.yaml